name: Build C++ Project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglfw3-dev libvulkan-dev vulkan-tools

    - name: Compile
      run: |
        g++ *.cpp -o sandbox.exe -lglfw -lvulkan -ldl -lpthread -lX11 -lXrandr -lXi -static-libgcc -static-libstdc++
        
