name: Build Windows EXE

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install MinGW and Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64 unzip curl

    - name: Clone Dependencies
      run: |
        git clone --depth 1 https://github.com/ocornut/imgui.git imgui_src
        git clone --depth 1 https://github.com/KhronosGroup/Vulkan-Headers.git vulkan_headers

    - name: Download GLFW for Windows
      run: |
        curl -L https://github.com/glfw/glfw/releases/download/3.4/glfw-3.4.bin.WIN64.zip -o glfw.zip
        unzip -q glfw.zip

    - name: Compile for Windows
      run: |
        # Автоматический поиск путей к GLFW, чтобы избежать ошибок с регистром
        GLFW_LIB=$(find . -name "libglfw3.a" | head -n 1)
        GLFW_INC=$(find . -type d -name "include" | grep glfw | head -n 1)
        
        echo "Found GLFW lib: $GLFW_LIB"
        echo "Found GLFW inc: $GLFW_INC"

        x86_64-w64-mingw32-g++ main.cpp gui.cpp \
            imgui_src/imgui.cpp \
            imgui_src/imgui_draw.cpp \
            imgui_src/imgui_tables.cpp \
            imgui_src/imgui_widgets.cpp \
            imgui_src/backends/imgui_impl_glfw.cpp \
            imgui_src/backends/imgui_impl_vulkan.cpp \
            -Iimgui_src \
            -Iimgui_src/backends \
            -I"$GLFW_INC" \
            -Ivulkan_headers/include \
            "$GLFW_LIB" \
            -o sandbox.exe \
            -lgdi32 -lopengl32 -limm32 -lole32 -luuid \
            -static-libgcc -static-libstdc++

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: sandbox-executable
        path: sandbox.exe
        
